apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-datasource
    isDefault: true
    editable: false  # Security best practice
    jsonData:
      maxLines: 5000
      timeout: 60s
      derivedFields:
        - datasourceUid: tempo  # Optional: Remove if no Tempo
          matcherRegex: "(?:trace_id|traceID)=([a-f0-9]+)"
          name: TraceID
          url: "$${__url.path}?orgId=1&left=%5B%22now-1h%22%2C%22now%22%2C%22Tempo%22%2C%7B%22query%22%3A%22$${__value.raw}%22%7D%5D"
          urlDisplayLabel: "View trace"
        - matcherRegex: "container_name=\"([^\"]+)\""
          name: Container
          url: "$${__url.path}?orgId=1&left=%5B%22now-1h%22%2C%22now%22%2C%22Loki%22%2C%7B%22expr%22%3A%22%7Bcontainer_name%3D%5C%22$${__value.raw}%5C%22%7D%22%7D%5D"
          urlDisplayLabel: "View container logs"
      alerting:
        enabled: true
    version: 1
